"""Report exporter — generates formatted .docx literature review"""
import io
from datetime import datetime
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement


def _heading(doc, text, level=1, color=None):
    h = doc.add_heading(text, level=level)
    if color and h.runs:
        h.runs[0].font.color.rgb = color
    return h


def _add_toc(doc):
    """Add a simple Table of Contents placeholder."""
    para = doc.add_paragraph()
    run = para.add_run("Table of Contents")
    run.bold = True
    run.font.size = Pt(14)
    doc.add_paragraph("(Navigate using document headings)")
    doc.add_paragraph()


def export_docx(state: dict) -> bytes:
    doc = Document()

    # Title page
    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = title_para.add_run(f"Literature Review: {state.get('topic', 'Research Topic')}")
    r.font.size = Pt(20)
    r.bold = True
    r.font.color.rgb = RGBColor(0x0F, 0x27, 0x44)

    doc.add_paragraph()
    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    meta.add_run(
        f"Generated by DeepResearch Agent\n"
        f"Nimra Tariq — AI Engineer & Assistant Professor\n"
        f"Superior University Lahore, Pakistan\n"
        f"github.com/nimra-pixel\n\n"
        f"Generated: {datetime.now().strftime('%B %d, %Y')}\n"
        f"Domain: {state.get('domain', 'General')}\n"
        f"Papers analyzed: {len(state.get('filtered_papers', []))}\n"
        f"Quality score: {state.get('critic_score', 0):.1f}/10"
    ).font.size = Pt(11)
    doc.add_page_break()

    # Abstract
    _heading(doc, "Abstract", 1, RGBColor(0x0F, 0x27, 0x44))
    abstract = state.get("abstract", "")
    if abstract:
        doc.add_paragraph(abstract)
    if state.get("urdu_abstract"):
        _heading(doc, "خلاصہ (Urdu Abstract)", 2)
        p = doc.add_paragraph(state["urdu_abstract"])
        p.runs[0].font.size = Pt(12)
    doc.add_paragraph()

    # Table of contents placeholder
    _add_toc(doc)
    doc.add_page_break()

    # Sections
    for sec in state.get("sections", []):
        _heading(doc, sec["title"], 1, RGBColor(0x0F, 0x27, 0x44))
        content = sec.get("content", "")
        for para_text in content.split("\n\n"):
            para_text = para_text.strip()
            if para_text:
                p = doc.add_paragraph(para_text)
                p.paragraph_format.first_line_indent = Inches(0.3)
        if sec.get("urdu_summary"):
            box = doc.add_paragraph()
            box.add_run("اردو خلاصہ: ").bold = True
            box.add_run(sec["urdu_summary"])
            box.paragraph_format.left_indent = Inches(0.5)
        doc.add_paragraph()

    # Research gaps
    gaps = state.get("research_gaps", [])
    if gaps:
        doc.add_page_break()
        _heading(doc, "Research Gaps Identified", 1, RGBColor(0x0F, 0x27, 0x44))
        priority_colors = {
            "high": RGBColor(0xDC, 0x26, 0x26),
            "medium": RGBColor(0xD9, 0x77, 0x06),
            "low": RGBColor(0x16, 0xA3, 0x4A),
        }
        for g in gaps:
            p = doc.add_paragraph()
            priority = g.get("priority", "medium")
            run = p.add_run(f"[{priority.upper()}] {g['gap']}")
            run.bold = True
            run.font.color.rgb = priority_colors.get(priority, RGBColor(0, 0, 0))
            doc.add_paragraph(f"Evidence: {g.get('evidence', '')}")
            doc.add_paragraph(f"Opportunity: {g.get('opportunity', '')}")
            doc.add_paragraph()

    # Future directions
    directions = state.get("future_directions", [])
    if directions:
        _heading(doc, "Future Research Directions", 1, RGBColor(0x0F, 0x27, 0x44))
        for d in directions:
            doc.add_paragraph(d, style="List Bullet")

    # References
    papers = state.get("filtered_papers", [])
    if papers:
        doc.add_page_break()
        _heading(doc, "References", 1, RGBColor(0x0F, 0x27, 0x44))
        for i, p in enumerate(papers, 1):
            authors = ", ".join(p.get("authors", [])[:3])
            if len(p.get("authors", [])) > 3:
                authors += " et al."
            ref = doc.add_paragraph(style="List Number")
            ref.add_run(f"{authors} ({p.get('year', 'n.d.')}). ").bold = False
            ref.add_run(f"{p['title']}. ").italic = True
            ref.add_run(f"{p['source'].upper()}.")
            if p.get("url"):
                ref.add_run(f" {p['url']}")

    # Critic feedback
    if state.get("critic_feedback"):
        doc.add_page_break()
        _heading(doc, "Quality Assessment", 1)
        doc.add_paragraph(state["critic_feedback"])

    # Footer disclaimer
    doc.add_paragraph()
    disc = doc.add_paragraph(
        "This literature review was autonomously generated by DeepResearch Agent. "
        "It is intended as a research aid and should be verified by domain experts before academic submission."
    )
    disc.runs[0].font.size = Pt(9)
    disc.runs[0].font.color.rgb = RGBColor(0x88, 0x88, 0x88)

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()
